name: hotel_mobile_app
description: "Hotel booking mobile application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  equatable: ^2.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  go_router: ^14.0.0
  url_launcher: ^6.2.5
  logger: ^2.0.2+1
  # Temporarily fixing carousel_slider conflict with Flutter's Carousel
  # https://github.com/flutter/flutter/issues/139427
  carousel_slider:
    git: 
      url: https://github.com/serenader2014/flutter_carousel_slider
      ref: master
  connectivity_plus: ^5.0.2
  flutter_rating_bar: ^4.0.1
  animate_do: ^3.3.3
  lottie: ^3.1.0
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  generate: true # Generates localization code
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
